// <auto-generated>
using System.Reflection;


namespace Microsoft.AspNetCore.Razor.Runtime
{
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>Must call '{2}.{1}' before calling '{2}.{0}'.</summary>
        internal static string ScopeManager_EndCannotBeCalledWithoutACallToBegin => GetResourceString("ScopeManager_EndCannotBeCalledWithoutACallToBegin");
        /// <summary>Must call '{2}.{1}' before calling '{2}.{0}'.</summary>
        internal static string FormatScopeManager_EndCannotBeCalledWithoutACallToBegin(object p0, object p1, object p2)
           => string.Format(Culture, GetResourceString("ScopeManager_EndCannotBeCalledWithoutACallToBegin"), p0, p1, p2);


    }
}
