// <auto-generated>
using System.Reflection;


namespace Microsoft.AspNetCore.Diagnostics
{
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>You are seeing this page because DiagnosticsPageMiddleware was added to your web application.</summary>
        internal static string DiagnosticsPageHtml_Information => GetResourceString("DiagnosticsPageHtml_Information");
        /// <summary>Test Error Message</summary>
        internal static string DiagnosticsPageHtml_TestErrorMessage => GetResourceString("DiagnosticsPageHtml_TestErrorMessage");
        /// <summary>Test Error Page</summary>
        internal static string DiagnosticsPageHtml_TestErrorSection => GetResourceString("DiagnosticsPageHtml_TestErrorSection");
        /// <summary>Diagnostics Page</summary>
        internal static string DiagnosticsPageHtml_Title => GetResourceString("DiagnosticsPageHtml_Title");
        /// <summary>Cookies</summary>
        internal static string ErrorPageHtml_CookiesButton => GetResourceString("ErrorPageHtml_CookiesButton");
        /// <summary>Headers</summary>
        internal static string ErrorPageHtml_HeadersButton => GetResourceString("ErrorPageHtml_HeadersButton");
        /// <summary>No cookie data.</summary>
        internal static string ErrorPageHtml_NoCookieData => GetResourceString("ErrorPageHtml_NoCookieData");
        /// <summary>No header data.</summary>
        internal static string ErrorPageHtml_NoHeaderData => GetResourceString("ErrorPageHtml_NoHeaderData");
        /// <summary>No query string data.</summary>
        internal static string ErrorPageHtml_NoQueryStringData => GetResourceString("ErrorPageHtml_NoQueryStringData");
        /// <summary>Query</summary>
        internal static string ErrorPageHtml_QueryButton => GetResourceString("ErrorPageHtml_QueryButton");
        /// <summary>Stack</summary>
        internal static string ErrorPageHtml_StackButton => GetResourceString("ErrorPageHtml_StackButton");
        /// <summary>Internal Server Error</summary>
        internal static string ErrorPageHtml_Title => GetResourceString("ErrorPageHtml_Title");
        /// <summary>An unhandled exception occurred while processing the request.</summary>
        internal static string ErrorPageHtml_UnhandledException => GetResourceString("ErrorPageHtml_UnhandledException");
        /// <summary>Unknown location</summary>
        internal static string ErrorPageHtml_UnknownLocation => GetResourceString("ErrorPageHtml_UnknownLocation");
        /// <summary>Value</summary>
        internal static string ErrorPageHtml_ValueColumn => GetResourceString("ErrorPageHtml_ValueColumn");
        /// <summary>Variable</summary>
        internal static string ErrorPageHtml_VariableColumn => GetResourceString("ErrorPageHtml_VariableColumn");
        /// <summary>The path must start with a '/'.</summary>
        internal static string Exception_PathMustStartWithSlash => GetResourceString("Exception_PathMustStartWithSlash");
        /// <summary>Name</summary>
        internal static string RuntimeInfoPage_PackageNameColumnName => GetResourceString("RuntimeInfoPage_PackageNameColumnName");
        /// <summary>Path</summary>
        internal static string RuntimeInfoPage_PackagePathColumnName => GetResourceString("RuntimeInfoPage_PackagePathColumnName");
        /// <summary>Packages:</summary>
        internal static string RuntimeInfoPage_Packages => GetResourceString("RuntimeInfoPage_Packages");
        /// <summary>Could not retrieve the list of loaded packages.</summary>
        internal static string RuntimeInfoPage_PackagesFail => GetResourceString("RuntimeInfoPage_PackagesFail");
        /// <summary>Version</summary>
        internal static string RuntimeInfoPage_PackageVersionColumnName => GetResourceString("RuntimeInfoPage_PackageVersionColumnName");
        /// <summary>Runtime Version:</summary>
        internal static string RuntimeInfoPage_RuntimeVersion => GetResourceString("RuntimeInfoPage_RuntimeVersion");
        /// <summary>Could not determine the runtime version.</summary>
        internal static string RuntimeInfoPage_RuntimeVersionFail => GetResourceString("RuntimeInfoPage_RuntimeVersionFail");
        /// <summary>Runtime Information</summary>
        internal static string RuntimeInfoPage_Title => GetResourceString("RuntimeInfoPage_Title");
        /// <summary>Welcome</summary>
        internal static string WelcomeHeader => GetResourceString("WelcomeHeader");
        /// <summary>Learn more about the Microsoft ASP.NET Core components</summary>
        internal static string WelcomeLearnMicrosoftAspNet => GetResourceString("WelcomeLearnMicrosoftAspNet");
        /// <summary>Browser</summary>
        internal static string WelcomePageImageText_Browser => GetResourceString("WelcomePageImageText_Browser");
        /// <summary>Learn More</summary>
        internal static string WelcomePageImageText_LearnMore => GetResourceString("WelcomePageImageText_LearnMore");
        /// <summary>Light Bulb</summary>
        internal static string WelcomePageImageText_LightBulb => GetResourceString("WelcomePageImageText_LightBulb");
        /// <summary>Skyline</summary>
        internal static string WelcomePageImageText_Skyline => GetResourceString("WelcomePageImageText_Skyline");
        /// <summary>Your ASP.NET Core application has been successfully started</summary>
        internal static string WelcomeStarted => GetResourceString("WelcomeStarted");
        /// <summary>Your ASP.NET Core application has been successfully started.</summary>
        internal static string WelcomeTitle => GetResourceString("WelcomeTitle");
        /// <summary>An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.</summary>
        internal static string ErrorPageHtml_CompilationException => GetResourceString("ErrorPageHtml_CompilationException");
        /// <summary>Operating System:</summary>
        internal static string RuntimeInfoPage_OperatingSystem => GetResourceString("RuntimeInfoPage_OperatingSystem");
        /// <summary>Runtime Architecture:</summary>
        internal static string RuntimeInfoPage_RuntimeArchitecture => GetResourceString("RuntimeInfoPage_RuntimeArchitecture");
        /// <summary>Runtime Type:</summary>
        internal static string RuntimeInfoPage_RuntimeType => GetResourceString("RuntimeInfoPage_RuntimeType");
        /// <summary>Could not determine the operating system.</summary>
        internal static string RuntimeInfoPage_OperatingSystemFail => GetResourceString("RuntimeInfoPage_OperatingSystemFail");
        /// <summary>Could not determine the runtime architecture.</summary>
        internal static string RuntimeInfoPage_RuntimeArchitectureFail => GetResourceString("RuntimeInfoPage_RuntimeArchitectureFail");
        /// <summary>Could not determine the runtime type.</summary>
        internal static string RuntimeInfoPage_RuntimeTypeFail => GetResourceString("RuntimeInfoPage_RuntimeTypeFail");
        /// <summary>Environment:</summary>
        internal static string RuntimeInfoPage_Environment => GetResourceString("RuntimeInfoPage_Environment");
        /// <summary>An error occurred when configuring the exception handler middleware. Either the 'ExceptionHandlingPath' or the 'ExceptionHandler' option must be set in 'UseExceptionHandler()'.</summary>
        internal static string ExceptionHandlerOptions_NotConfiguredCorrectly => GetResourceString("ExceptionHandlerOptions_NotConfiguredCorrectly");
        /// <summary>No route values.</summary>
        internal static string ErrorPageHtml_NoRouteValues => GetResourceString("ErrorPageHtml_NoRouteValues");
        /// <summary>Routing</summary>
        internal static string ErrorPageHtml_RoutingButton => GetResourceString("ErrorPageHtml_RoutingButton");
        /// <summary>Endpoint</summary>
        internal static string ErrorPageHtml_Endpoint => GetResourceString("ErrorPageHtml_Endpoint");
        /// <summary>Display Name</summary>
        internal static string ErrorPageHtml_EndpointDisplayName => GetResourceString("ErrorPageHtml_EndpointDisplayName");
        /// <summary>Route Order</summary>
        internal static string ErrorPageHtml_EndpointRouteOrder => GetResourceString("ErrorPageHtml_EndpointRouteOrder");
        /// <summary>Route HTTP Method</summary>
        internal static string ErrorPageHtml_EndpointRouteHttpMethod => GetResourceString("ErrorPageHtml_EndpointRouteHttpMethod");
        /// <summary>Route Pattern</summary>
        internal static string ErrorPageHtml_EndpointRoutePattern => GetResourceString("ErrorPageHtml_EndpointRoutePattern");
        /// <summary>No endpoint.</summary>
        internal static string ErrorPageHtml_NoEndpoint => GetResourceString("ErrorPageHtml_NoEndpoint");
        /// <summary>Route Values</summary>
        internal static string ErrorPageHtml_RouteValues => GetResourceString("ErrorPageHtml_RouteValues");
        /// <summary>Name</summary>
        internal static string ErrorPageHtml_NameColumn => GetResourceString("ErrorPageHtml_NameColumn");

    }
}
