// <auto-generated>
using System.Reflection;


namespace Microsoft.AspNetCore.StaticFiles
{
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>No formatter provided.</summary>
        internal static string Args_NoFormatter => GetResourceString("Args_NoFormatter");
        /// <summary>Index of</summary>
        internal static string HtmlDir_IndexOf => GetResourceString("HtmlDir_IndexOf");
        /// <summary>Last Modified</summary>
        internal static string HtmlDir_LastModified => GetResourceString("HtmlDir_LastModified");
        /// <summary>Modified</summary>
        internal static string HtmlDir_Modified => GetResourceString("HtmlDir_Modified");
        /// <summary>Name</summary>
        internal static string HtmlDir_Name => GetResourceString("HtmlDir_Name");
        /// <summary>Size</summary>
        internal static string HtmlDir_Size => GetResourceString("HtmlDir_Size");
        /// <summary>The list of files in the given directory.  Column headers are listed in the first row.</summary>
        internal static string HtmlDir_TableSummary => GetResourceString("HtmlDir_TableSummary");

    }
}
