// <auto-generated>
using System.Reflection;


namespace Microsoft.Extensions.Configuration.CommandLine
{
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>Keys in switch mappings are case-insensitive. A duplicated key '{0}' was found.</summary>
        internal static string Error_DuplicatedKeyInSwitchMappings => GetResourceString("Error_DuplicatedKeyInSwitchMappings");
        /// <summary>Keys in switch mappings are case-insensitive. A duplicated key '{0}' was found.</summary>
        internal static string FormatError_DuplicatedKeyInSwitchMappings(object p0)
           => string.Format(Culture, GetResourceString("Error_DuplicatedKeyInSwitchMappings"), p0);

        /// <summary>The switch mappings contain an invalid switch '{0}'.</summary>
        internal static string Error_InvalidSwitchMapping => GetResourceString("Error_InvalidSwitchMapping");
        /// <summary>The switch mappings contain an invalid switch '{0}'.</summary>
        internal static string FormatError_InvalidSwitchMapping(object p0)
           => string.Format(Culture, GetResourceString("Error_InvalidSwitchMapping"), p0);

        /// <summary>The short switch '{0}' is not defined in the switch mappings.</summary>
        internal static string Error_ShortSwitchNotDefined => GetResourceString("Error_ShortSwitchNotDefined");
        /// <summary>The short switch '{0}' is not defined in the switch mappings.</summary>
        internal static string FormatError_ShortSwitchNotDefined(object p0)
           => string.Format(Culture, GetResourceString("Error_ShortSwitchNotDefined"), p0);


    }
}
