// <auto-generated>
using System.Reflection;


namespace Microsoft.AspNetCore.DataProtection.Abstractions
{
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>The payload was invalid.</summary>
        internal static string CryptCommon_PayloadInvalid => GetResourceString("CryptCommon_PayloadInvalid");
        /// <summary>The purposes collection cannot be null or empty and cannot contain null elements.</summary>
        internal static string DataProtectionExtensions_NullPurposesCollection => GetResourceString("DataProtectionExtensions_NullPurposesCollection");
        /// <summary>An error occurred during a cryptographic operation.</summary>
        internal static string CryptCommon_GenericError => GetResourceString("CryptCommon_GenericError");
        /// <summary>No service for type '{0}' has been registered.</summary>
        internal static string DataProtectionExtensions_NoService => GetResourceString("DataProtectionExtensions_NoService");
        /// <summary>No service for type '{0}' has been registered.</summary>
        internal static string FormatDataProtectionExtensions_NoService(object p0)
           => string.Format(Culture, GetResourceString("DataProtectionExtensions_NoService"), p0);


    }
}
