// <auto-generated>
using System.Reflection;


namespace Microsoft.AspNetCore.WebUtilities
{
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>The stream must support reading.</summary>
        internal static string HttpRequestStreamReader_StreamNotReadable => GetResourceString("HttpRequestStreamReader_StreamNotReadable");
        /// <summary>The stream must support writing.</summary>
        internal static string HttpResponseStreamWriter_StreamNotWritable => GetResourceString("HttpResponseStreamWriter_StreamNotWritable");
        /// <summary>Invalid {0}, {1} or {2} length.</summary>
        internal static string WebEncoders_InvalidCountOffsetOrLength => GetResourceString("WebEncoders_InvalidCountOffsetOrLength");
        /// <summary>Invalid {0}, {1} or {2} length.</summary>
        internal static string FormatWebEncoders_InvalidCountOffsetOrLength(object p0, object p1, object p2)
           => string.Format(Culture, GetResourceString("WebEncoders_InvalidCountOffsetOrLength"), p0, p1, p2);


    }
}
