// <auto-generated>
using System.Reflection;


namespace Microsoft.AspNetCore.Server.IIS
{
    internal static partial class CoreStrings
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(CoreStrings)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>Cannot write to response body after connection has been upgraded.</summary>
        internal static string ResponseStreamWasUpgraded => GetResourceString("ResponseStreamWasUpgraded");
        /// <summary>The response has been aborted due to an unhandled application exception.</summary>
        internal static string UnhandledApplicationException => GetResourceString("UnhandledApplicationException");
        /// <summary>Cannot upgrade a non-upgradable request. Check IHttpUpgradeFeature.IsUpgradableRequest to determine if a request can be upgraded.</summary>
        internal static string CannotUpgradeNonUpgradableRequest => GetResourceString("CannotUpgradeNonUpgradableRequest");
        /// <summary>IHttpUpgradeFeature.UpgradeAsync was already called and can only be called once per connection.</summary>
        internal static string UpgradeCannotBeCalledMultipleTimes => GetResourceString("UpgradeCannotBeCalledMultipleTimes");
        /// <summary>Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.</summary>
        internal static string SynchronousReadsDisallowed => GetResourceString("SynchronousReadsDisallowed");
        /// <summary>Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.</summary>
        internal static string SynchronousWritesDisallowed => GetResourceString("SynchronousWritesDisallowed");
        /// <summary>Cannot write to the response body, the response has completed.</summary>
        internal static string WritingToResponseBodyAfterResponseCompleted => GetResourceString("WritingToResponseBodyAfterResponseCompleted");
        /// <summary>The connection was aborted by the application.</summary>
        internal static string ConnectionAbortedByApplication => GetResourceString("ConnectionAbortedByApplication");
        /// <summary>The connection or stream was aborted because a write operation was aborted with a CancellationToken.</summary>
        internal static string ConnectionOrStreamAbortedByCancellationToken => GetResourceString("ConnectionOrStreamAbortedByCancellationToken");
        /// <summary>{name} cannot be set because the response has already started.</summary>
        internal static string ParameterReadOnlyAfterResponseStarted => GetResourceString("ParameterReadOnlyAfterResponseStarted");
        /// <summary>{name} cannot be set because the response has already started.</summary>
        internal static string FormatParameterReadOnlyAfterResponseStarted(object name)
           => string.Format(Culture, GetResourceString("ParameterReadOnlyAfterResponseStarted", new [] { "name" }), name);

        /// <summary>Request body too large.</summary>
        internal static string BadRequest_RequestBodyTooLarge => GetResourceString("BadRequest_RequestBodyTooLarge");
        /// <summary>The maximum request body size cannot be modified after the app has already started reading from the request body.</summary>
        internal static string MaxRequestBodySizeCannotBeModifiedAfterRead => GetResourceString("MaxRequestBodySizeCannotBeModifiedAfterRead");
        /// <summary>The maximum request body size cannot be modified after the request has been upgraded.</summary>
        internal static string MaxRequestBodySizeCannotBeModifiedForUpgradedRequests => GetResourceString("MaxRequestBodySizeCannotBeModifiedForUpgradedRequests");
        /// <summary>Value must be null or a non-negative number.</summary>
        internal static string NonNegativeNumberOrNullRequired => GetResourceString("NonNegativeNumberOrNullRequired");
        /// <summary>Bad request.</summary>
        internal static string BadRequest => GetResourceString("BadRequest");
        /// <summary>Increasing the MaxRequestBodySize conflicts with the max value for IIS limit maxAllowedContentLength. HTTP requests that have a content length greater than maxAllowedContentLength will still be rejected by IIS. You can disable the limit by either removing  ...</summary>
        internal static string MaxRequestLimitWarning => GetResourceString("MaxRequestLimitWarning");

    }
}
