// <auto-generated>
using System.Reflection;


namespace Microsoft.Extensions.Http
{
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>The '{0}' function must return a non-null policy instance. To create a policy that takes no action, use '{1}'.</summary>
        internal static string PolicyHttpMessageHandler_PolicySelector_ReturnedNull => GetResourceString("PolicyHttpMessageHandler_PolicySelector_ReturnedNull");
        /// <summary>The '{0}' function must return a non-null policy instance. To create a policy that takes no action, use '{1}'.</summary>
        internal static string FormatPolicyHttpMessageHandler_PolicySelector_ReturnedNull(object p0, object p1)
           => string.Format(Culture, GetResourceString("PolicyHttpMessageHandler_PolicySelector_ReturnedNull"), p0, p1);


    }
}
