// <auto-generated>
using System.Reflection;


namespace Microsoft.AspNetCore.Identity.EntityFrameworkCore
{
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>[ProtectedPersonalData] only works strings by default.</summary>
        internal static string CanOnlyProtectStrings => GetResourceString("CanOnlyProtectStrings");
        /// <summary>AddEntityFrameworkStores can only be called with a role that derives from IdentityRole&lt;TKey&gt;.</summary>
        internal static string NotIdentityRole => GetResourceString("NotIdentityRole");
        /// <summary>AddEntityFrameworkStores can only be called with a user that derives from IdentityUser&lt;TKey&gt;.</summary>
        internal static string NotIdentityUser => GetResourceString("NotIdentityUser");
        /// <summary>Role {0} does not exist.</summary>
        internal static string RoleNotFound => GetResourceString("RoleNotFound");
        /// <summary>Role {0} does not exist.</summary>
        internal static string FormatRoleNotFound(object p0)
           => string.Format(Culture, GetResourceString("RoleNotFound"), p0);

        /// <summary>Value cannot be null or empty.</summary>
        internal static string ValueCannotBeNullOrEmpty => GetResourceString("ValueCannotBeNullOrEmpty");

    }
}
